package com.example.mapper;

//import com.example.domain.Department;
//import com.example.example.DepartmentExample;
//
//import java.util.List;
//import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table departments
//     *
//     * @mbggenerated Tue May 26 12:58:48 JST 2020
//     */
//    int countByExample(DepartmentExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table departments
//     *
//     * @mbggenerated Tue May 26 12:58:48 JST 2020
//     */
//    int deleteByExample(DepartmentExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table departments
//     *
//     * @mbggenerated Tue May 26 12:58:48 JST 2020
//     */
//    int deleteByPrimaryKey(Integer departmentId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table departments
//     *
//     * @mbggenerated Tue May 26 12:58:48 JST 2020
//     */
//    int insert(Department record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table departments
//     *
//     * @mbggenerated Tue May 26 12:58:48 JST 2020
//     */
//    int insertSelective(Department record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table departments
//     *
//     * @mbggenerated Tue May 26 12:58:48 JST 2020
//     */
//
//    List<Department> selectByExample(DepartmentExample example);
//
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table departments
//     *
//     * @mbggenerated Tue May 26 12:58:48 JST 2020
//     */
//    Department selectByPrimaryKey(Integer departmentId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table departments
//     *
//     * @mbggenerated Tue May 26 12:58:48 JST 2020
//     */
//
//    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table departments
//     *
//     * @mbggenerated Tue May 26 12:58:48 JST 2020
//     */
//    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);
//
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table departments
//     *
//     * @mbggenerated Tue May 26 12:58:48 JST 2020
//     */
//    int updateByPrimaryKeySelective(Department record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table departments
//     *
//     * @mbggenerated Tue May 26 12:58:48 JST 2020
//     */
//    int updateByPrimaryKey(Department record);
}