package com.example.example;

import java.util.ArrayList;
import java.util.List;

public class HadPersonalityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    public HadPersonalityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHadPersonalityIdIsNull() {
            addCriterion("had_personality_id is null");
            return (Criteria) this;
        }

        public Criteria andHadPersonalityIdIsNotNull() {
            addCriterion("had_personality_id is not null");
            return (Criteria) this;
        }

        public Criteria andHadPersonalityIdEqualTo(Integer value) {
            addCriterion("had_personality_id =", value, "hadPersonalityId");
            return (Criteria) this;
        }

        public Criteria andHadPersonalityIdNotEqualTo(Integer value) {
            addCriterion("had_personality_id <>", value, "hadPersonalityId");
            return (Criteria) this;
        }

        public Criteria andHadPersonalityIdGreaterThan(Integer value) {
            addCriterion("had_personality_id >", value, "hadPersonalityId");
            return (Criteria) this;
        }

        public Criteria andHadPersonalityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("had_personality_id >=", value, "hadPersonalityId");
            return (Criteria) this;
        }

        public Criteria andHadPersonalityIdLessThan(Integer value) {
            addCriterion("had_personality_id <", value, "hadPersonalityId");
            return (Criteria) this;
        }

        public Criteria andHadPersonalityIdLessThanOrEqualTo(Integer value) {
            addCriterion("had_personality_id <=", value, "hadPersonalityId");
            return (Criteria) this;
        }

        public Criteria andHadPersonalityIdIn(List<Integer> values) {
            addCriterion("had_personality_id in", values, "hadPersonalityId");
            return (Criteria) this;
        }

        public Criteria andHadPersonalityIdNotIn(List<Integer> values) {
            addCriterion("had_personality_id not in", values, "hadPersonalityId");
            return (Criteria) this;
        }

        public Criteria andHadPersonalityIdBetween(Integer value1, Integer value2) {
            addCriterion("had_personality_id between", value1, value2, "hadPersonalityId");
            return (Criteria) this;
        }

        public Criteria andHadPersonalityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("had_personality_id not between", value1, value2, "hadPersonalityId");
            return (Criteria) this;
        }

        public Criteria andStatusIdIsNull() {
            addCriterion("status_id is null");
            return (Criteria) this;
        }

        public Criteria andStatusIdIsNotNull() {
            addCriterion("status_id is not null");
            return (Criteria) this;
        }

        public Criteria andStatusIdEqualTo(Integer value) {
            addCriterion("status_id =", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotEqualTo(Integer value) {
            addCriterion("status_id <>", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdGreaterThan(Integer value) {
            addCriterion("status_id >", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("status_id >=", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdLessThan(Integer value) {
            addCriterion("status_id <", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdLessThanOrEqualTo(Integer value) {
            addCriterion("status_id <=", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdIn(List<Integer> values) {
            addCriterion("status_id in", values, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotIn(List<Integer> values) {
            addCriterion("status_id not in", values, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdBetween(Integer value1, Integer value2) {
            addCriterion("status_id between", value1, value2, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotBetween(Integer value1, Integer value2) {
            addCriterion("status_id not between", value1, value2, "statusId");
            return (Criteria) this;
        }

        public Criteria andPersonalityIdIsNull() {
            addCriterion("personality_id is null");
            return (Criteria) this;
        }

        public Criteria andPersonalityIdIsNotNull() {
            addCriterion("personality_id is not null");
            return (Criteria) this;
        }

        public Criteria andPersonalityIdEqualTo(Integer value) {
            addCriterion("personality_id =", value, "personalityId");
            return (Criteria) this;
        }

        public Criteria andPersonalityIdNotEqualTo(Integer value) {
            addCriterion("personality_id <>", value, "personalityId");
            return (Criteria) this;
        }

        public Criteria andPersonalityIdGreaterThan(Integer value) {
            addCriterion("personality_id >", value, "personalityId");
            return (Criteria) this;
        }

        public Criteria andPersonalityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("personality_id >=", value, "personalityId");
            return (Criteria) this;
        }

        public Criteria andPersonalityIdLessThan(Integer value) {
            addCriterion("personality_id <", value, "personalityId");
            return (Criteria) this;
        }

        public Criteria andPersonalityIdLessThanOrEqualTo(Integer value) {
            addCriterion("personality_id <=", value, "personalityId");
            return (Criteria) this;
        }

        public Criteria andPersonalityIdIn(List<Integer> values) {
            addCriterion("personality_id in", values, "personalityId");
            return (Criteria) this;
        }

        public Criteria andPersonalityIdNotIn(List<Integer> values) {
            addCriterion("personality_id not in", values, "personalityId");
            return (Criteria) this;
        }

        public Criteria andPersonalityIdBetween(Integer value1, Integer value2) {
            addCriterion("personality_id between", value1, value2, "personalityId");
            return (Criteria) this;
        }

        public Criteria andPersonalityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("personality_id not between", value1, value2, "personalityId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table had_personalities
     *
     * @mbggenerated do_not_delete_during_merge Tue May 26 13:18:16 JST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table had_personalities
     *
     * @mbggenerated Tue May 26 13:18:16 JST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}