package com.example.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserExample {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String stage) {
			if (stage == null) {
				throw new RuntimeException("Value for stage cannot be null");
			}
			criteria.add(new Criterion(stage));
		}

		protected void addCriterion(String stage, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(stage, value));
		}

		protected void addCriterion(String stage, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(stage, value1, value2));
		}

		protected void addCriterionForJDBCDate(String stage, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(stage, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String stage, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(stage, dateList, property);
		}

		protected void addCriterionForJDBCDate(String stage, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(stage, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andHiredOnIsNull() {
			addCriterion("hired_on is null");
			return (Criteria) this;
		}

		public Criteria andHiredOnIsNotNull() {
			addCriterion("hired_on is not null");
			return (Criteria) this;
		}

		public Criteria andHiredOnEqualTo(Date value) {
			addCriterionForJDBCDate("hired_on =", value, "hiredOn");
			return (Criteria) this;
		}

		public Criteria andHiredOnNotEqualTo(Date value) {
			addCriterionForJDBCDate("hired_on <>", value, "hiredOn");
			return (Criteria) this;
		}

		public Criteria andHiredOnGreaterThan(Date value) {
			addCriterionForJDBCDate("hired_on >", value, "hiredOn");
			return (Criteria) this;
		}

		public Criteria andHiredOnGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("hired_on >=", value, "hiredOn");
			return (Criteria) this;
		}

		public Criteria andHiredOnLessThan(Date value) {
			addCriterionForJDBCDate("hired_on <", value, "hiredOn");
			return (Criteria) this;
		}

		public Criteria andHiredOnLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("hired_on <=", value, "hiredOn");
			return (Criteria) this;
		}

		public Criteria andHiredOnIn(List<Date> values) {
			addCriterionForJDBCDate("hired_on in", values, "hiredOn");
			return (Criteria) this;
		}

		public Criteria andHiredOnNotIn(List<Date> values) {
			addCriterionForJDBCDate("hired_on not in", values, "hiredOn");
			return (Criteria) this;
		}

		public Criteria andHiredOnBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("hired_on between", value1, value2, "hiredOn");
			return (Criteria) this;
		}

		public Criteria andHiredOnNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("hired_on not between", value1, value2, "hiredOn");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdIsNull() {
			addCriterion("department_id is null");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdIsNotNull() {
			addCriterion("department_id is not null");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdEqualTo(Integer value) {
			addCriterion("department_id =", value, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdNotEqualTo(Integer value) {
			addCriterion("department_id <>", value, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdGreaterThan(Integer value) {
			addCriterion("department_id >", value, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("department_id >=", value, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdLessThan(Integer value) {
			addCriterion("department_id <", value, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdLessThanOrEqualTo(Integer value) {
			addCriterion("department_id <=", value, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdIn(List<Integer> values) {
			addCriterion("department_id in", values, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdNotIn(List<Integer> values) {
			addCriterion("department_id not in", values, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdBetween(Integer value1, Integer value2) {
			addCriterion("department_id between", value1, value2, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdNotBetween(Integer value1, Integer value2) {
			addCriterion("department_id not between", value1, value2, "departmentId");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}
		
		public Criteria andStageIsNull() {
			addCriterion("stage is null");
			return (Criteria) this;
		}

		public Criteria andStageIsNotNull() {
			addCriterion("stage is not null");
			return (Criteria) this;
		}

		public Criteria andStageEqualTo(String value) {
			addCriterion("stage =", value, "stage");
			return (Criteria) this;
		}

		public Criteria andStageNotEqualTo(String value) {
			addCriterion("stage <>", value, "stage");
			return (Criteria) this;
		}

		public Criteria andStageGreaterThan(String value) {
			addCriterion("stage >", value, "stage");
			return (Criteria) this;
		}

		public Criteria andStageGreaterThanOrEqualTo(String value) {
			addCriterion("stage >=", value, "stage");
			return (Criteria) this;
		}

		public Criteria andStageLessThan(String value) {
			addCriterion("stage <", value, "stage");
			return (Criteria) this;
		}

		public Criteria andStageLessThanOrEqualTo(String value) {
			addCriterion("stage <=", value, "stage");
			return (Criteria) this;
		}

		public Criteria andStageLike(String value) {
			addCriterion("stage like", value, "stage");
			return (Criteria) this;
		}

		public Criteria andStageNotLike(String value) {
			addCriterion("stage not like", value, "stage");
			return (Criteria) this;
		}

		public Criteria andStageIn(List<String> values) {
			addCriterion("stage in", values, "stage");
			return (Criteria) this;
		}

		public Criteria andStageNotIn(List<String> values) {
			addCriterion("stage not in", values, "stage");
			return (Criteria) this;
		}

		public Criteria andStageBetween(String value1, String value2) {
			addCriterion("stage between", value1, value2, "stage");
			return (Criteria) this;
		}

		public Criteria andStageNotBetween(String value1, String value2) {
			addCriterion("stage not between", value1, value2, "stage");
			return (Criteria) this;
		}

		public Criteria andUpdatedPasswordAtIsNull() {
			addCriterion("updated_password_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedPasswordAtIsNotNull() {
			addCriterion("updated_password_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedPasswordAtEqualTo(Date value) {
			addCriterionForJDBCDate("updated_password_at =", value, "updatedPasswordAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedPasswordAtNotEqualTo(Date value) {
			addCriterionForJDBCDate("updated_password_at <>", value, "updatedPasswordAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedPasswordAtGreaterThan(Date value) {
			addCriterionForJDBCDate("updated_password_at >", value, "updatedPasswordAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedPasswordAtGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("updated_password_at >=", value, "updatedPasswordAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedPasswordAtLessThan(Date value) {
			addCriterionForJDBCDate("updated_password_at <", value, "updatedPasswordAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedPasswordAtLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("updated_password_at <=", value, "updatedPasswordAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedPasswordAtIn(List<Date> values) {
			addCriterionForJDBCDate("updated_password_at in", values, "updatedPasswordAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedPasswordAtNotIn(List<Date> values) {
			addCriterionForJDBCDate("updated_password_at not in", values, "updatedPasswordAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedPasswordAtBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("updated_password_at between", value1, value2, "updatedPasswordAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedPasswordAtNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("updated_password_at not between", value1, value2, "updatedPasswordAt");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNull() {
			addCriterion("creator is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNotNull() {
			addCriterion("creator is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorEqualTo(String value) {
			addCriterion("creator =", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotEqualTo(String value) {
			addCriterion("creator <>", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThan(String value) {
			addCriterion("creator >", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThanOrEqualTo(String value) {
			addCriterion("creator >=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThan(String value) {
			addCriterion("creator <", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThanOrEqualTo(String value) {
			addCriterion("creator <=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLike(String value) {
			addCriterion("creator like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotLike(String value) {
			addCriterion("creator not like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorIn(List<String> values) {
			addCriterion("creator in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotIn(List<String> values) {
			addCriterion("creator not in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorBetween(String value1, String value2) {
			addCriterion("creator between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotBetween(String value1, String value2) {
			addCriterion("creator not between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdaterIsNull() {
			addCriterion("updater is null");
			return (Criteria) this;
		}

		public Criteria andUpdaterIsNotNull() {
			addCriterion("updater is not null");
			return (Criteria) this;
		}

		public Criteria andUpdaterEqualTo(String value) {
			addCriterion("updater =", value, "updater");
			return (Criteria) this;
		}

		public Criteria andUpdaterNotEqualTo(String value) {
			addCriterion("updater <>", value, "updater");
			return (Criteria) this;
		}

		public Criteria andUpdaterGreaterThan(String value) {
			addCriterion("updater >", value, "updater");
			return (Criteria) this;
		}

		public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
			addCriterion("updater >=", value, "updater");
			return (Criteria) this;
		}

		public Criteria andUpdaterLessThan(String value) {
			addCriterion("updater <", value, "updater");
			return (Criteria) this;
		}

		public Criteria andUpdaterLessThanOrEqualTo(String value) {
			addCriterion("updater <=", value, "updater");
			return (Criteria) this;
		}

		public Criteria andUpdaterLike(String value) {
			addCriterion("updater like", value, "updater");
			return (Criteria) this;
		}

		public Criteria andUpdaterNotLike(String value) {
			addCriterion("updater not like", value, "updater");
			return (Criteria) this;
		}

		public Criteria andUpdaterIn(List<String> values) {
			addCriterion("updater in", values, "updater");
			return (Criteria) this;
		}

		public Criteria andUpdaterNotIn(List<String> values) {
			addCriterion("updater not in", values, "updater");
			return (Criteria) this;
		}

		public Criteria andUpdaterBetween(String value1, String value2) {
			addCriterion("updater between", value1, value2, "updater");
			return (Criteria) this;
		}

		public Criteria andUpdaterNotBetween(String value1, String value2) {
			addCriterion("updater not between", value1, value2, "updater");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table users
	 *
	 * @mbggenerated do_not_delete_during_merge Tue May 26 13:00:00 JST 2020
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table users
	 *
	 * @mbggenerated Tue May 26 13:00:00 JST 2020
	 */
	public static class Criterion {
		private String stage;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		public String getstage() {
			return stage;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		protected Criterion(String stage) {
			super();
			this.stage = stage;
			this.noValue = true;
		}

		protected Criterion(String stage, Object value) {
			super();
			this.stage = stage;
			this.value = value;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String stage, Object value, Object secondValue) {
			super();
			this.stage = stage;
			this.value = value;
			this.secondValue = secondValue;
			this.betweenValue = true;
		}
	}
}